services:
  reservations:
    build:
      context: .
      dockerfile: ./apps/reservations/DockerFile
      target: development
    command: pnpm run start:dev reservations
    env_file:
      - ./apps/reservations/.env
    ports:
      - '3000:3000'
    volumes:
      - ./apps/reservations:/app/apps/reservations # Mount the reservations app code
      - /app/node_modules
  auth:
    build:
      context: .
      dockerfile: ./apps/auth/DockerFile
      target: development
    command: pnpm run start:dev auth
    env_file:
      - ./apps/auth/.env
    ports:
      - '3001:3001'
    volumes:
      - ./apps/auth:/app/apps/auth # Mount the reservations app code
      - /app/node_modules
  mongo:
    image: mongo
    ports:
      - '27017:27017'
