# Dockerfile
# Use official Node.js image as a base
FROM node:alpine AS development

# Set working directory
WORKDIR /app

# Copy package.json and package-lock.json
COPY package.json ./
COPY pnpm-lock.yaml ./

# Install dependencies
RUN npm install -g pnpm

RUN pnpm install


# Copy rest of the application code
COPY . .



# Build the Next.js app
RUN pnpm run build

FROM node:alpine AS production

ARG NODE_ENV=production
ENV NODE_ENV=${NODE_ENV}

WORKDIR /app

# Copy package.json and package-lock.json
COPY package.json ./
COPY pnpm-lock.yaml ./

# Install dependencies
RUN npm install -g pnpm

RUN pnpm install --prod


COPY --from=development /app/dist ./dist

CMD ["node","dist/apps/auth/main"]